name: Clean storybook

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  remove-folder:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          ref: gh-pages
      - name: Remove ${{ github.head_ref }} folder
        run: |
          rm -rf ${{ github.head_ref }}
          git commit -m "Remove ${{ github.head_ref }}"
          git push
