name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.1
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Branch name
        run: echo ${{ github.head_ref }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: ${{ github.head_ref }}
