name: Build and Deploy

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.1
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: ${{ github.head_ref || 'main' }}
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Preview available at <https://milton-cazoo.github.io/poc-storybook-environments/${{ github.head_ref }}>
