name: Build and Deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.1
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: ${{ github.head_ref || 'main' }}
  remove-folder:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          ref: gh-pages
      - name: Remove ${{ github.head_ref }} folder
        run: rm -rf ${{ github.head_ref }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          commit_message: Remove ${{ github.head_ref }}
          commit_options: "--no-verify"
